export const CASE_STATUSES = {
  RECEIVED: "received",
  WAITING_PART: "waiting_part",
  DIAGNOSING: "diagnosing",
  WAITING_APPROVAL: "waiting_approval",
  IN_PROGRESS: "in_progress",
  REPAIRED: "repaired",
  NOT_REPAIRABLE: "not_repairable",
  COMPLETED: "completed",
  DELIVERED: "delivered",
  ARCHIVED: "archived",
} as const;

export type CaseStatus = typeof CASE_STATUSES[keyof typeof CASE_STATUSES];

export const ALLOWED_TRANSITIONS: Record<CaseStatus, CaseStatus[]> = {
  [CASE_STATUSES.RECEIVED]: [CASE_STATUSES.WAITING_PART, CASE_STATUSES.DIAGNOSING, CASE_STATUSES.NOT_REPAIRABLE],
  [CASE_STATUSES.WAITING_PART]: [CASE_STATUSES.RECEIVED, CASE_STATUSES.DIAGNOSING, CASE_STATUSES.NOT_REPAIRABLE],
  [CASE_STATUSES.DIAGNOSING]: [
    CASE_STATUSES.WAITING_PART,
    CASE_STATUSES.WAITING_APPROVAL,
    CASE_STATUSES.NOT_REPAIRABLE,
  ],
  [CASE_STATUSES.WAITING_APPROVAL]: [CASE_STATUSES.DIAGNOSING, CASE_STATUSES.IN_PROGRESS, CASE_STATUSES.NOT_REPAIRABLE, CASE_STATUSES.ARCHIVED],
  [CASE_STATUSES.IN_PROGRESS]: [CASE_STATUSES.REPAIRED, CASE_STATUSES.NOT_REPAIRABLE],
  [CASE_STATUSES.REPAIRED]: [CASE_STATUSES.COMPLETED],
  [CASE_STATUSES.NOT_REPAIRABLE]: [
    CASE_STATUSES.DIAGNOSING,
    CASE_STATUSES.WAITING_PART,
    CASE_STATUSES.COMPLETED,
    CASE_STATUSES.ARCHIVED,
  ],
  [CASE_STATUSES.COMPLETED]: [CASE_STATUSES.DELIVERED, CASE_STATUSES.ARCHIVED],
  [CASE_STATUSES.DELIVERED]: [CASE_STATUSES.ARCHIVED],
  [CASE_STATUSES.ARCHIVED]: [], // No transitions from archived
};
